name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - staging

jobs:
  lint-test-build:
    name: Lint, Test, and Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install pnpm
        run: corepack enable pnpm

      - name: Install dependencies
        run: pnpm install
        env:
          PNPM_FLAGS: '--shamefully-hoist'

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test

      - name: Build for Nuxt
        run: pnpm build
        env:
          NODE_ENV: production

      - name: Upload production build
        if: github.ref == 'refs/heads/staging'
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: .output

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: lint-test-build

    steps:
      - name: Download production build
        uses: actions/download-artifact@v3
        with:
          name: production-build
          path: .output

      - name: Deploy to Netlify
        run: npx netlify-cli deploy --dir=.output --prodIfUnlocked
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

