name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - staging

jobs:
  
  # Build job (runs after lint and test)
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      # Cache node_modules and pnpm-store
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          name: production-build
          path: .output

  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest
    needs: lint-test-build

    steps:
      - name: Download production build
        uses: actions/download-artifact@v3
        with:
          name: production-build
          path: .output

      - name: Deploy to Netlify
        run: netlify deploy --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

